-- Only fill legacy reviews with missing photos. Existing account photos are untouched.
begin;
create temporary table avatar_before on commit drop as select id, user_photo from public.reviews;
create temporary table avatar_assignment (first_id bigint primary key, photo_url text not null) on commit drop;
insert into avatar_assignment values
    (403, 'https://jokiin.my.id/assets/review-avatars/legacy-403.jpg'),
    (404, 'https://jokiin.my.id/assets/review-avatars/legacy-404.jpg'),
    (405, 'https://jokiin.my.id/assets/review-avatars/legacy-405.jpg'),
    (406, 'https://jokiin.my.id/assets/review-avatars/legacy-406.jpg'),
    (407, 'https://jokiin.my.id/assets/review-avatars/legacy-407.jpg'),
    (408, 'https://jokiin.my.id/assets/review-avatars/legacy-408.jpg'),
    (409, 'https://jokiin.my.id/assets/review-avatars/legacy-409.jpg'),
    (410, 'https://jokiin.my.id/assets/review-avatars/legacy-410.jpg'),
    (411, 'https://jokiin.my.id/assets/review-avatars/legacy-411.jpg'),
    (412, 'https://jokiin.my.id/assets/review-avatars/legacy-412.jpg'),
    (413, 'https://jokiin.my.id/assets/review-avatars/legacy-413.jpg'),
    (414, 'https://jokiin.my.id/assets/review-avatars/legacy-414.jpg'),
    (415, 'https://jokiin.my.id/assets/review-avatars/legacy-415.jpg'),
    (416, 'https://jokiin.my.id/assets/review-avatars/legacy-416.jpg'),
    (417, 'https://jokiin.my.id/assets/review-avatars/legacy-417.jpg'),
    (418, 'https://jokiin.my.id/assets/review-avatars/legacy-418.jpg'),
    (419, 'https://jokiin.my.id/assets/review-avatars/legacy-419.jpg'),
    (420, 'https://jokiin.my.id/assets/review-avatars/legacy-420.jpg'),
    (421, 'https://jokiin.my.id/assets/review-avatars/legacy-421.jpg'),
    (422, 'https://jokiin.my.id/assets/review-avatars/legacy-422.jpg'),
    (423, 'https://jokiin.my.id/assets/review-avatars/legacy-423.jpg'),
    (424, 'https://jokiin.my.id/assets/review-avatars/legacy-424.jpg'),
    (425, 'https://jokiin.my.id/assets/review-avatars/legacy-425.jpg'),
    (426, 'https://jokiin.my.id/assets/review-avatars/legacy-426.jpg'),
    (427, 'https://jokiin.my.id/assets/review-avatars/legacy-427.jpg'),
    (429, 'https://jokiin.my.id/assets/review-avatars/legacy-429.jpg'),
    (430, 'https://jokiin.my.id/assets/review-avatars/legacy-430.jpg'),
    (431, 'https://jokiin.my.id/assets/review-avatars/legacy-431.svg'),
    (432, 'https://jokiin.my.id/assets/review-avatars/legacy-432.jpg'),
    (434, 'https://jokiin.my.id/assets/review-avatars/legacy-434.jpg'),
    (435, 'https://jokiin.my.id/assets/review-avatars/legacy-435.jpg'),
    (436, 'https://jokiin.my.id/assets/review-avatars/legacy-436.jpg'),
    (437, 'https://jokiin.my.id/assets/review-avatars/legacy-437.svg'),
    (438, 'https://jokiin.my.id/assets/review-avatars/legacy-438.svg'),
    (439, 'https://jokiin.my.id/assets/review-avatars/legacy-439.jpg'),
    (440, 'https://jokiin.my.id/assets/review-avatars/legacy-440.jpg'),
    (441, 'https://jokiin.my.id/assets/review-avatars/legacy-441.svg'),
    (442, 'https://jokiin.my.id/assets/review-avatars/legacy-442.svg'),
    (443, 'https://jokiin.my.id/assets/review-avatars/legacy-443.jpg'),
    (445, 'https://jokiin.my.id/assets/review-avatars/legacy-445.svg'),
    (446, 'https://jokiin.my.id/assets/review-avatars/legacy-446.svg'),
    (447, 'https://jokiin.my.id/assets/review-avatars/legacy-447.jpg'),
    (448, 'https://jokiin.my.id/assets/review-avatars/legacy-448.svg'),
    (449, 'https://jokiin.my.id/assets/review-avatars/legacy-449.svg'),
    (451, 'https://jokiin.my.id/assets/review-avatars/default.jpg'),
    (452, 'https://jokiin.my.id/assets/review-avatars/default.jpg'),
    (453, 'https://jokiin.my.id/assets/review-avatars/legacy-453.svg'),
    (454, 'https://jokiin.my.id/assets/review-avatars/legacy-454.jpg'),
    (455, 'https://jokiin.my.id/assets/review-avatars/legacy-455.svg'),
    (456, 'https://jokiin.my.id/assets/review-avatars/legacy-456.svg'),
    (457, 'https://jokiin.my.id/assets/review-avatars/legacy-457.svg'),
    (458, 'https://jokiin.my.id/assets/review-avatars/legacy-458.svg'),
    (459, 'https://jokiin.my.id/assets/review-avatars/legacy-459.svg'),
    (460, 'https://jokiin.my.id/assets/review-avatars/legacy-460.svg'),
    (461, 'https://jokiin.my.id/assets/review-avatars/default.jpg'),
    (462, 'https://jokiin.my.id/assets/review-avatars/legacy-462.svg'),
    (463, 'https://jokiin.my.id/assets/review-avatars/legacy-463.svg'),
    (464, 'https://jokiin.my.id/assets/review-avatars/legacy-464.svg'),
    (465, 'https://jokiin.my.id/assets/review-avatars/legacy-465.svg'),
    (466, 'https://jokiin.my.id/assets/review-avatars/legacy-466.svg'),
    (467, 'https://jokiin.my.id/assets/review-avatars/legacy-467.svg'),
    (468, 'https://jokiin.my.id/assets/review-avatars/legacy-468.svg'),
    (469, 'https://jokiin.my.id/assets/review-avatars/legacy-469.svg'),
    (471, 'https://jokiin.my.id/assets/review-avatars/legacy-471.svg'),
    (472, 'https://jokiin.my.id/assets/review-avatars/legacy-472.svg'),
    (474, 'https://jokiin.my.id/assets/review-avatars/legacy-474.svg'),
    (477, 'https://jokiin.my.id/assets/review-avatars/legacy-477.svg'),
    (478, 'https://jokiin.my.id/assets/review-avatars/legacy-478.svg'),
    (479, 'https://jokiin.my.id/assets/review-avatars/legacy-479.svg'),
    (480, 'https://jokiin.my.id/assets/review-avatars/legacy-480.svg'),
    (481, 'https://jokiin.my.id/assets/review-avatars/legacy-481.svg'),
    (482, 'https://jokiin.my.id/assets/review-avatars/default.jpg'),
    (483, 'https://jokiin.my.id/assets/review-avatars/legacy-483.svg'),
    (484, 'https://jokiin.my.id/assets/review-avatars/legacy-484.svg'),
    (485, 'https://jokiin.my.id/assets/review-avatars/legacy-485.svg'),
    (486, 'https://jokiin.my.id/assets/review-avatars/legacy-486.svg'),
    (488, 'https://jokiin.my.id/assets/review-avatars/legacy-488.svg'),
    (489, 'https://jokiin.my.id/assets/review-avatars/legacy-489.svg'),
    (490, 'https://jokiin.my.id/assets/review-avatars/legacy-490.svg'),
    (491, 'https://jokiin.my.id/assets/review-avatars/legacy-491.svg'),
    (492, 'https://jokiin.my.id/assets/review-avatars/legacy-492.svg'),
    (493, 'https://jokiin.my.id/assets/review-avatars/legacy-493.svg'),
    (494, 'https://jokiin.my.id/assets/review-avatars/legacy-494.svg'),
    (496, 'https://jokiin.my.id/assets/review-avatars/legacy-496.svg'),
    (498, 'https://jokiin.my.id/assets/review-avatars/legacy-498.svg'),
    (499, 'https://jokiin.my.id/assets/review-avatars/legacy-499.svg'),
    (501, 'https://jokiin.my.id/assets/review-avatars/legacy-501.svg'),
    (502, 'https://jokiin.my.id/assets/review-avatars/legacy-502.svg'),
    (503, 'https://jokiin.my.id/assets/review-avatars/legacy-503.svg'),
    (504, 'https://jokiin.my.id/assets/review-avatars/default.jpg'),
    (505, 'https://jokiin.my.id/assets/review-avatars/legacy-505.svg'),
    (506, 'https://jokiin.my.id/assets/review-avatars/default.jpg'),
    (507, 'https://jokiin.my.id/assets/review-avatars/legacy-507.svg'),
    (508, 'https://jokiin.my.id/assets/review-avatars/legacy-508.svg'),
    (509, 'https://jokiin.my.id/assets/review-avatars/default.jpg'),
    (512, 'https://jokiin.my.id/assets/review-avatars/legacy-512.svg'),
    (513, 'https://jokiin.my.id/assets/review-avatars/legacy-513.svg'),
    (514, 'https://jokiin.my.id/assets/review-avatars/legacy-514.svg'),
    (515, 'https://jokiin.my.id/assets/review-avatars/legacy-515.svg'),
    (516, 'https://jokiin.my.id/assets/review-avatars/legacy-516.svg'),
    (517, 'https://jokiin.my.id/assets/review-avatars/legacy-517.svg'),
    (518, 'https://jokiin.my.id/assets/review-avatars/legacy-518.svg'),
    (519, 'https://jokiin.my.id/assets/review-avatars/legacy-519.svg'),
    (520, 'https://jokiin.my.id/assets/review-avatars/legacy-520.svg'),
    (521, 'https://jokiin.my.id/assets/review-avatars/legacy-521.svg'),
    (522, 'https://jokiin.my.id/assets/review-avatars/legacy-522.svg'),
    (525, 'https://jokiin.my.id/assets/review-avatars/legacy-525.svg'),
    (526, 'https://jokiin.my.id/assets/review-avatars/legacy-526.svg'),
    (527, 'https://jokiin.my.id/assets/review-avatars/legacy-527.svg'),
    (528, 'https://jokiin.my.id/assets/review-avatars/legacy-528.svg'),
    (529, 'https://jokiin.my.id/assets/review-avatars/default.jpg'),
    (532, 'https://jokiin.my.id/assets/review-avatars/legacy-532.svg'),
    (533, 'https://jokiin.my.id/assets/review-avatars/legacy-533.svg'),
    (534, 'https://jokiin.my.id/assets/review-avatars/legacy-534.svg'),
    (535, 'https://jokiin.my.id/assets/review-avatars/legacy-535.svg'),
    (536, 'https://jokiin.my.id/assets/review-avatars/legacy-536.svg'),
    (537, 'https://jokiin.my.id/assets/review-avatars/legacy-537.svg'),
    (538, 'https://jokiin.my.id/assets/review-avatars/legacy-538.svg'),
    (539, 'https://jokiin.my.id/assets/review-avatars/legacy-539.svg'),
    (540, 'https://jokiin.my.id/assets/review-avatars/legacy-540.svg'),
    (541, 'https://jokiin.my.id/assets/review-avatars/legacy-541.svg'),
    (543, 'https://jokiin.my.id/assets/review-avatars/legacy-543.svg'),
    (546, 'https://jokiin.my.id/assets/review-avatars/legacy-546.svg'),
    (549, 'https://jokiin.my.id/assets/review-avatars/legacy-549.svg'),
    (550, 'https://jokiin.my.id/assets/review-avatars/legacy-550.svg'),
    (551, 'https://jokiin.my.id/assets/review-avatars/legacy-551.svg'),
    (552, 'https://jokiin.my.id/assets/review-avatars/legacy-552.svg'),
    (554, 'https://jokiin.my.id/assets/review-avatars/legacy-554.svg'),
    (555, 'https://jokiin.my.id/assets/review-avatars/legacy-555.svg'),
    (556, 'https://jokiin.my.id/assets/review-avatars/legacy-556.svg'),
    (558, 'https://jokiin.my.id/assets/review-avatars/legacy-558.svg'),
    (559, 'https://jokiin.my.id/assets/review-avatars/legacy-559.svg'),
    (561, 'https://jokiin.my.id/assets/review-avatars/legacy-561.svg'),
    (562, 'https://jokiin.my.id/assets/review-avatars/legacy-562.svg'),
    (563, 'https://jokiin.my.id/assets/review-avatars/legacy-563.svg'),
    (564, 'https://jokiin.my.id/assets/review-avatars/legacy-564.svg'),
    (565, 'https://jokiin.my.id/assets/review-avatars/legacy-565.svg'),
    (566, 'https://jokiin.my.id/assets/review-avatars/legacy-566.svg'),
    (567, 'https://jokiin.my.id/assets/review-avatars/legacy-567.svg'),
    (568, 'https://jokiin.my.id/assets/review-avatars/legacy-568.svg'),
    (570, 'https://jokiin.my.id/assets/review-avatars/legacy-570.svg'),
    (571, 'https://jokiin.my.id/assets/review-avatars/legacy-571.svg'),
    (572, 'https://jokiin.my.id/assets/review-avatars/legacy-572.svg'),
    (574, 'https://jokiin.my.id/assets/review-avatars/legacy-574.svg'),
    (575, 'https://jokiin.my.id/assets/review-avatars/legacy-575.svg'),
    (576, 'https://jokiin.my.id/assets/review-avatars/legacy-576.svg'),
    (577, 'https://jokiin.my.id/assets/review-avatars/legacy-577.svg'),
    (578, 'https://jokiin.my.id/assets/review-avatars/legacy-578.svg'),
    (579, 'https://jokiin.my.id/assets/review-avatars/legacy-579.svg'),
    (580, 'https://jokiin.my.id/assets/review-avatars/legacy-580.svg'),
    (581, 'https://jokiin.my.id/assets/review-avatars/legacy-581.svg'),
    (582, 'https://jokiin.my.id/assets/review-avatars/legacy-582.svg'),
    (584, 'https://jokiin.my.id/assets/review-avatars/legacy-584.svg'),
    (585, 'https://jokiin.my.id/assets/review-avatars/legacy-585.svg'),
    (587, 'https://jokiin.my.id/assets/review-avatars/legacy-587.svg'),
    (588, 'https://jokiin.my.id/assets/review-avatars/legacy-588.svg'),
    (589, 'https://jokiin.my.id/assets/review-avatars/legacy-589.svg'),
    (590, 'https://jokiin.my.id/assets/review-avatars/legacy-590.svg'),
    (591, 'https://jokiin.my.id/assets/review-avatars/legacy-591.svg'),
    (594, 'https://jokiin.my.id/assets/review-avatars/legacy-594.svg'),
    (596, 'https://jokiin.my.id/assets/review-avatars/legacy-596.svg'),
    (598, 'https://jokiin.my.id/assets/review-avatars/legacy-598.svg'),
    (600, 'https://jokiin.my.id/assets/review-avatars/legacy-600.svg'),
    (601, 'https://jokiin.my.id/assets/review-avatars/legacy-601.svg'),
    (602, 'https://jokiin.my.id/assets/review-avatars/legacy-602.svg'),
    (603, 'https://jokiin.my.id/assets/review-avatars/legacy-603.svg'),
    (606, 'https://jokiin.my.id/assets/review-avatars/legacy-606.svg'),
    (607, 'https://jokiin.my.id/assets/review-avatars/legacy-607.svg'),
    (608, 'https://jokiin.my.id/assets/review-avatars/legacy-608.svg'),
    (609, 'https://jokiin.my.id/assets/review-avatars/legacy-609.svg'),
    (610, 'https://jokiin.my.id/assets/review-avatars/legacy-610.svg'),
    (611, 'https://jokiin.my.id/assets/review-avatars/legacy-611.svg'),
    (612, 'https://jokiin.my.id/assets/review-avatars/legacy-612.svg'),
    (613, 'https://jokiin.my.id/assets/review-avatars/legacy-613.svg'),
    (614, 'https://jokiin.my.id/assets/review-avatars/legacy-614.svg'),
    (615, 'https://jokiin.my.id/assets/review-avatars/legacy-615.svg'),
    (617, 'https://jokiin.my.id/assets/review-avatars/legacy-617.svg'),
    (618, 'https://jokiin.my.id/assets/review-avatars/legacy-618.svg'),
    (619, 'https://jokiin.my.id/assets/review-avatars/legacy-619.svg'),
    (620, 'https://jokiin.my.id/assets/review-avatars/legacy-620.svg'),
    (622, 'https://jokiin.my.id/assets/review-avatars/legacy-622.svg'),
    (623, 'https://jokiin.my.id/assets/review-avatars/legacy-623.svg'),
    (624, 'https://jokiin.my.id/assets/review-avatars/legacy-624.svg'),
    (625, 'https://jokiin.my.id/assets/review-avatars/legacy-625.svg'),
    (626, 'https://jokiin.my.id/assets/review-avatars/legacy-626.svg'),
    (627, 'https://jokiin.my.id/assets/review-avatars/legacy-627.svg'),
    (628, 'https://jokiin.my.id/assets/review-avatars/legacy-628.svg'),
    (630, 'https://jokiin.my.id/assets/review-avatars/legacy-630.svg'),
    (631, 'https://jokiin.my.id/assets/review-avatars/legacy-631.svg'),
    (632, 'https://jokiin.my.id/assets/review-avatars/legacy-632.svg'),
    (633, 'https://jokiin.my.id/assets/review-avatars/legacy-633.svg'),
    (634, 'https://jokiin.my.id/assets/review-avatars/legacy-634.svg'),
    (636, 'https://jokiin.my.id/assets/review-avatars/legacy-636.svg'),
    (637, 'https://jokiin.my.id/assets/review-avatars/legacy-637.svg'),
    (638, 'https://jokiin.my.id/assets/review-avatars/legacy-638.svg'),
    (639, 'https://jokiin.my.id/assets/review-avatars/legacy-639.svg'),
    (641, 'https://jokiin.my.id/assets/review-avatars/legacy-641.svg'),
    (642, 'https://jokiin.my.id/assets/review-avatars/legacy-642.svg'),
    (643, 'https://jokiin.my.id/assets/review-avatars/legacy-643.svg'),
    (644, 'https://jokiin.my.id/assets/review-avatars/legacy-644.svg'),
    (645, 'https://jokiin.my.id/assets/review-avatars/legacy-645.svg'),
    (647, 'https://jokiin.my.id/assets/review-avatars/legacy-647.svg'),
    (648, 'https://jokiin.my.id/assets/review-avatars/legacy-648.svg'),
    (649, 'https://jokiin.my.id/assets/review-avatars/legacy-649.svg'),
    (650, 'https://jokiin.my.id/assets/review-avatars/legacy-650.svg'),
    (652, 'https://jokiin.my.id/assets/review-avatars/legacy-652.svg');
with customers as (
    select customer_name, min(id) as first_id from public.reviews where user_id is null group by customer_name
)
update public.reviews r set user_photo = a.photo_url
from customers c join avatar_assignment a using (first_id)
where r.customer_name = c.customer_name and r.user_id is null and nullif(trim(r.user_photo), '') is null;
do $$
begin
    if exists (
        select 1 from avatar_before b join public.reviews r using (id)
        where nullif(trim(b.user_photo), '') is not null and r.user_photo is distinct from b.user_photo
    ) then raise exception 'Existing profile photos changed'; end if;
    if (select count(*) from public.reviews where user_photo in (select photo_url from avatar_assignment)) <> 251 then
        raise exception 'Unexpected number of assigned reviews';
    end if;
    if (select count(distinct customer_name) from public.reviews where user_photo = 'https://jokiin.my.id/assets/review-avatars/default.jpg') <> 8 then
        raise exception 'Expected exactly 8 default-avatar customers';
    end if;
    if exists (
        select customer_name from public.reviews where user_photo in (select photo_url from avatar_assignment)
        group by customer_name having count(distinct user_photo) <> 1
    ) then raise exception 'Inconsistent avatar for a customer'; end if;
end $$;
commit;
